### ISSUE TITLE
"tempest cleanup --init-saved-state" failed with ussuri/candidate rev 417

### ISSUE THREAD

**Issue by jeffreychang911** [canonical/snap-tempest#168] opened 2024-05-03 03:47 UTC
Tried to run snap tempest from ussuri/candidate rev 417 on top of Openstack ussuri-focal, and "tempest cleanup --init-saved-state" failed.
SolQA test run - https://solutions.qa.canonical.com/testruns/eb3188a3-ce5d-47dc-8541-92adaea447a4
Artifacts - https://oil-jenkins.canonical.com/artifacts/eb3188a3-ce5d-47dc-8541-92adaea447a4/index.html

Error logs
2024-05-03-03:30:29 root DEBUG [localhost]: tempest cleanup --init-saved-state
2024-05-03-03:30:35 root ERROR [localhost] Command failed: tempest cleanup --init-saved-state
2024-05-03-03:30:35 root ERROR 1[localhost] STDOUT follows:
b''
2024-05-03-03:30:35 root ERROR 2[localhost] STDERR follows:
Failure during cleanup
Traceback (most recent call last):
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/cmd/cleanup.py", line 109, in take_action
    self.init(parsed_args)
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/cmd/cleanup.py", line 146, in init
    self._init_admin_ids()
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/cmd/cleanup.py", line 239, in _init_admin_ids
    user = identity.get_user_by_project(us_cl, rla_cl,
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/common/identity.py", line 57, in get_user_by_project
    raise lib_exc.NotFound('No such user(%s) in %s' % (username, users))
tempest.lib.exceptions.NotFound: Object not found
Details: No such user(admin) in [{'email': 'juju@localhost', 'id': '73042e1bef4747a7a44da945db720fcb', 'name': 'admin', 'domain_id': 'a8a64a78e58d459884acbe7f26d3d285', 'enabled': True, 'password_expires_at': None, 'options': {}, 'links': {'self': 'https://keystone.silo5.lab1.solutionsqa:5000/v3/users/73042e1bef4747a7a44da945db720fcb'}}]
Traceback (most recent call last):
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/cmd/cleanup.py", line 109, in take_action
    self.init(parsed_args)
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/cmd/cleanup.py", line 146, in init
    self._init_admin_ids()
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/cmd/cleanup.py", line 239, in _init_admin_ids
    user = identity.get_user_by_project(us_cl, rla_cl,
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/common/identity.py", line 57, in get_user_by_project
    raise lib_exc.NotFound('No such user(%s) in %s' % (username, users))
tempest.lib.exceptions.NotFound: Object not found
Details: No such user(admin) in [{'email': 'juju@localhost', 'id': '73042e1bef4747a7a44da945db720fcb', 'name': 'admin', 'domain_id': 'a8a64a78e58d459884acbe7f26d3d285', 'enabled': True, 'password_expires_at': None, 'options': {}, 'links': {'self': 'https://keystone.silo5.lab1.solutionsqa:5000/v3/users/73042e1bef4747a7a44da945db720fcb'}}]

Traceback (most recent call last):
  File "/usr/local/bin/fce", line 33, in <module>
    sys.exit(load_entry_point('foundationcloudengine', 'console_scripts', 'fce')())
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/main.py", line 217, in entry_point
    sys.exit(main(sys.argv[1:]))
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/main.py", line 208, in main
    opts.func(opts)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/command.py", line 91, in run
    self.run_per_layer(layer, args)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/commands/validate.py", line 23, in run_per_layer
    layer.validate(tests=args.validators)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/baselayer.py", line 280, in validate
    ran_validator = self.validate_inner(*args, **kwargs)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/baselayer.py", line 265, in validate_inner
    validator.run()
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/baselayer.py", line 528, in run
    self.run_inner()
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/openstacklayer.py", line 341, in run_inner
    self.initialize()
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/openstacklayer.py", line 379, in initialize
    local(["tempest", "cleanup", "--init-saved-state"], cwd=self.tempest_path)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/remotehelpers.py", line 278, in local
    return run_cmd(cmd, target_machine, **kwargs)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/remotehelpers.py", line 209, in run_cmd
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['tempest', 'cleanup', '--init-saved-state']' returned non-zero exit status 1.

**Comment by jeffreychang911** [comment] 2024-05-03 04:24
ok, same error with snap tempest on ussuri/stable rev 190.
But we have successful run with yoga/candidate rev 377.

**Comment by chanchiwai-ray** [comment] 2024-05-31 03:04
I can confirm the behavior @jeffreychang911 was seeing for rev 190 (not working) and rev 377 (working). However, I can also confirm that the error is happening in the upstream `tempest==31.0.0.` (corresponding to tempest snap rev 190) but not on `tempest==37.0.0` (corresponding to tempest snap rev 377). This is probably an upstream issue https://bugs.launchpad.net/tempest/+bug/2003125, and they fixed it in `tempest==34.0.0`. So, if I am not mistaken, it should work with snap-tempest in channel xena or above.

**Comment by chanchiwai-ray** [comment] 2024-05-31 03:06
I am closing this because it was an upstream issue and it was fixed in the upstream starting from `tempest>=34.0.0` (or snap tempest xena and above)

**Closed by chanchiwai-ray** 2024-05-31 03:06 UTC
Labels: bug
